name: Merge PR and Exclude extension.ts

on: [pull_request]
jobs:
  merge_and_exclude:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge changes
        run: git merge --no-ff --no-commit <merge-branch>

      - name: Remove extension.ts from index
        run: git checkout -- myfile.txt

      - name: Commit changes
        run: |
          git commit -m "merged <merge-branch>"
        
