name: Merge PR and Exclude extension.ts

on:
  pull_request:
    types:
      - closed

jobs:
  merge_and_exclude:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge changes
        run: git merge --no-ff ${{ github.event.pull_request.head.sha }}

      - name: Remove extension.ts from index
        run: git rm --cached extension.ts

      - name: Commit changes
        run: |
          git commit -m "Merged PR excluding extension.ts"
          git push
