name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
      - name: Ignore extension.ts file during merge request
        run: |
          git merge --no-commit ${{ github.event.pull_request.head.ref }}
          git reset HEAD extension.ts
          git checkout -- extension.ts
          git commit -m "merged ${{ github.event.pull_request.head.ref }}"
