name: Ignore database-config.xml

on:
  pull_request:
    paths:
      - '**/database-config.xml'

jobs:
  check_config_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check for database-config.xml changes
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          if echo "$CHANGED_FILES" | grep -q '^database-config.xml$'; then
            echo "Error: You're trying to modify database-config.xml. This file cannot be modified during a pull request."
            exit 1
          fi
