name: Merge with Ignore

 

on:
  pull_request:
    types:
      - synchronize

 

jobs:
  merge:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

 

      - name: Merge changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git merge --no-ff ${{ github.event.pull_request.head.sha }}

 

      - name: Ignore specific file changes
        run: git checkout HEAD -- database_config.xml

 

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am "Merged PR and removed changes to database_config.xml"
